### PR TITLE
2015-10-2

### PR DESCRIPTION
**Pull request by michaeldupuisjr**
_This is an example._

Adds an article about Ember Data 2.0.

Adds a good overview of Ecto associations and embeds.

### CODE REVIEW

**Comment by michaeldupuisjr** [comment]
Imagine a week full of lively discussions regarding the articles!

**Comment by michaeldupuisjr** [comment]
It's now end of day Friday – someone can merge this PR and close it.

**Comment by michaeldupuisjr** [comment]
It's now end of day Friday – this PR can be merged!

**Comment by linstula** [comment]
:clap:

**Pull request merged**
